# This file was generated by GoReleaser. DO NOT EDIT.
cask "cache-cleaner" do
  name "cache-cleaner"
  desc "Collection of Go CLI tools for reclaiming disk space on development machines"
  homepage "https://github.com/markcallen/cache-cleaner"
  version "1.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dev-cache"
  binary "git-cleaner"
  binary "mac-cache-cleaner"

  on_macos do
    on_intel do
      url "https://github.com/markcallen/cache-cleaner/releases/download/v#{version}/cache-cleaner-#{version}-darwin-amd64.tar.gz"
      sha256 "6612d2f8d5fe582591968a9c6f4f0f6f2f42edb9cb8b467050020b5ca9680fbd"
    end
    on_arm do
      url "https://github.com/markcallen/cache-cleaner/releases/download/v#{version}/cache-cleaner-#{version}-darwin-arm64.tar.gz"
      sha256 "d28933a9c774602235bd6724b17bbcbdf6634c54cb88a4a0edacc6553a4c7644"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev-cache"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-cleaner"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mac-cache-cleaner"]
    end
  end

  caveats do
    "cache-cleaner includes three utilities:"
    "  • dev-cache     - Scans for project cache directories"
    "  • git-cleaner   - Finds and optimizes .git directories"
    "  • mac-cache-cleaner - Runs safe cleanup commands for developer tools"
    ""
    "Quick start:"
    "  dev-cache --init"
    "  git-cleaner --scan ~/src"
    "  mac-cache-cleaner --init"
    ""
    "Documentation: https://github.com/markcallen/cache-cleaner"
  end

  # No zap stanza required
end
