# This file was generated by GoReleaser. DO NOT EDIT.
cask "cache-cleaner" do
  name "cache-cleaner"
  desc "Collection of Go CLI tools for reclaiming disk space on development machines"
  homepage "https://github.com/markcallen/cache-cleaner"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dev-cache"
  binary "git-cleaner"
  binary "mac-cache-cleaner"

  on_macos do
    on_intel do
      url "https://github.com/markcallen/cache-cleaner/releases/download/v#{version}/cache-cleaner-#{version}-darwin-amd64.tar.gz"
      sha256 "1796bb74ab7e62bd341cddcdd9801384be9304a747e788635ff7ad0639148c66"
    end
    on_arm do
      url "https://github.com/markcallen/cache-cleaner/releases/download/v#{version}/cache-cleaner-#{version}-darwin-arm64.tar.gz"
      sha256 "23dab6e79a7436920b64fefd4d7b6d6f75a90073e9a6a678275c2cf6b1a4a526"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dev-cache"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-cleaner"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mac-cache-cleaner"]
    end
  end

  caveats do
    "cache-cleaner includes three utilities:"
    "  • dev-cache     - Scans for project cache directories"
    "  • git-cleaner   - Finds and optimizes .git directories"
    "  • mac-cache-cleaner - Runs safe cleanup commands for developer tools"
    ""
    "Quick start:"
    "  dev-cache --init"
    "  git-cleaner --scan ~/src"
    "  mac-cache-cleaner --init"
    ""
    "Documentation: https://github.com/markcallen/cache-cleaner"
  end

  # No zap stanza required
end
